### PR TITLE
Enhance audio, small shadow adjust

### PR DESCRIPTION
**Pull request by cameron-louw**

### CODE REVIEW

**Comment by cameron-louw** [comment]
Enhanced the audio quality and made a minor suggestion with the shadow (80% transparency)

**Comment by shaneel-kumar** [comment]
Audio was bugging me too so nice work!

**Review by shaneel-kumar — COMMENTED** [review]
I like the subtlety of the shadow

**Comment by cameron-louw** [comment]
Brennan suggested it. Hehe i showed him. He likes the project 😝

**Pull request merged**
